### ISSUE TITLE
Build fails if package is already present in the anaconda channel

### ISSUE THREAD

**Issue by Jorge-C** [biocore/conda-recipes#29]
Not sure what's happening b/c if it was already present it shouldn't try building it either.

```
2015-11-05 03:05:26,938 INFO: Uploading: anaconda -t {token} upload -u {channel} {built}

Using anaconda-server api site https://api.anaconda.org

detecting package type ...

conda

extracting package attributes for upload ...

done

Uploading file biocore/minced/0.2.0/osx-64/minced-0.2.0-1.tar.bz2 ... 

Distribution already exists. Please use the -i/--interactive or --force options or `anaconda remove biocore/minced/0.2.0/osx-64/minced-0.2.0-1.tar.bz2`

[Conflict] (u'file osx-64/minced-0.2.0-1.tar.bz2 already exists for package minced version 0.2.0', 409)

Traceback (most recent call last):

  File "ci/main.py", line 133, in <module>

    build_upload_recipes(sys.argv[1], sys.argv[2])

  File "ci/main.py", line 50, in build_upload_recipes

    upload(name, version, channel)

  File "ci/main.py", line 129, in upload

    shell=True)

  File "/Users/travis/miniconda/lib/python2.7/subprocess.py", line 540, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'anaconda -t ze-b2e094e1-af48-4b13-a678-ac6f0e5e9581 upload -u biocore /Users/travis/miniconda/conda-bld/osx-64/minced-0.2.0-1.tar.bz2' returned non-zero exit status 1

The command "python ci/main.py recipes biocore" exited with 1.
```

**Comment by RNAer** [comment]
ref #30 . oh man, it is trial and error with conda and travis... It is an easy fix. @Jorge-C , would u like to do it?

**Comment by RNAer** [comment]
@Jorge-C ，I'd be happy to do it if you are tied up currently :-)

**Comment by Jorge-C** [comment]
I'll have time to work on it tomorrow! Feel free to do it tonight if you
want to though.

**Comment by RNAer** [comment]
cool. just did it.
